import json, pathlib, shutil, urllib.request, concurrent.futures, csv, datetime
ROOT=pathlib.Path(__file__).resolve().parents[1]
P=json.loads((ROOT/'data/products.json').read_text())['products']
def write(path,s):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding='utf-8')
def schema(name,settings=[]):return '\n{% schema %}'+json.dumps({'name':name,'settings':settings,'presets':[{'name':name}]})+'{% endschema %}'
def section(name,body,settings=[]):write('theme/sections/'+name+'.liquid',body+schema(name.replace('-',' ').title(),settings))
def template(name,sections):write('theme/templates/'+name+'.json',json.dumps({'sections':{str(i):{'type':s} for i,s in enumerate(sections)},'order':[str(i) for i in range(len(sections))]},indent=2))
for d in ['assets','config','layout','locales','sections','snippets','templates']:(ROOT/'theme'/d).mkdir(parents=True,exist_ok=True)
assets=[]
for p in P:
 for i,img in enumerate(p['images']):
  name=p['handle']+'-'+str(i)+'.'+img['src'].split('?')[0].split('.')[-1]
  assets.append((img['src']+'&width=1400',name));img['local']=name
def download(pair):
 url,name=pair;path=ROOT/'theme/assets'/name
 if not path.exists():urllib.request.urlretrieve(url,path)
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:list(pool.map(download,assets))
write('data/catalog.json',json.dumps(P,indent=2))
write('data/provenance.json',json.dumps({'source':'https://essaint.com/products.json?limit=250','retrieved_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'products':len(P),'variants':sum(len(p['variants']) for p in P),'notes':'Public storefront snapshot; inventory quantities and private Shopify fields are not exposed. Page 2 verified empty. Theme uses live Shopify data.'},indent=2))
with (ROOT/'data/products.csv').open('w',newline='',encoding='utf-8-sig') as f:
 fields=['Handle','Title','Body (HTML)','Vendor','Product Category','Type','Tags','Published','Option1 Name','Option1 Value','Option2 Name','Option2 Value','Option3 Name','Option3 Value','Variant SKU','Variant Price','Variant Compare At Price','Variant Requires Shipping','Variant Taxable','Image Src','Image Position','Status']
 w=csv.DictWriter(f,fieldnames=fields);w.writeheader()
 for p in P:
  for i in range(max(len(p['variants']),len(p['images']))):
   row={'Handle':p['handle']}
   if i==0:row.update({'Title':p['title'],'Body (HTML)':p['body_html'],'Vendor':p['vendor'],'Type':p['product_type'],'Tags':', '.join(p['tags']),'Published':'FALSE','Status':'draft'})
   if i<len(p['variants']):
    v=p['variants'][i];row.update({'Variant SKU':v.get('sku') or '', 'Variant Price':v['price'],'Variant Compare At Price':v.get('compare_at_price') or '', 'Variant Requires Shipping':'TRUE','Variant Taxable':'TRUE'})
    for n,opt in enumerate(p['options'],1):row['Option'+str(n)+' Name']=opt['name'];row['Option'+str(n)+' Value']=v.get('option'+str(n)) or ''
   if i<len(p['images']):row.update({'Image Src':p['images'][i]['src'],'Image Position':i+1})
   w.writerow(row)
header='''<div class="announcement"><span>Proudly crafted in Lebanon</span><span>Complimentary shipping on orders over $100</span><span>7-day easy exchanges</span></div>
<header class="header"><a class="wordmark" href="{{ routes.root_url }}" aria-label="Essaint home">essaint<span>®</span></a><nav aria-label="Main navigation"><a href="{{ routes.all_products_collection_url }}">Shop all</a><a href="{{ routes.root_url }}#essentials">The essentials</a><a href="{{ routes.root_url }}#bundles">The outfit edit</a><a href="{{ routes.root_url }}#story">Our world</a></nav><div class="header-actions"><button data-search aria-label="Search products">{% render 'icon', name: 'search' %}</button><button data-cart aria-label="Open shopping bag">{% render 'icon', name: 'bag' %}<span data-count>{{ cart.item_count }}</span></button><button class="mobile-menu" data-menu aria-label="Open menu" aria-expanded="false">☰</button></div></header>'''
section('header',header)
write('theme/snippets/icon.liquid','''<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">{% if name == 'search' %}<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>{% else %}<path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>{% endif %}</svg>''')
hero='''<section class="hero"><div class="hero-copy"><p class="eyebrow">THE EVERYDAY COLLECTION / ESSAINT</p><h1>{{ section.settings.heading }}</h1><p class="hero-description">Considered cuts. Effortless combinations.<br>Your everyday, a little more elevated.</p><a class="button" href="{{ routes.all_products_collection_url }}">Discover the collection <span>↗</span></a><div class="hero-foot"><span>DESIGNED TO GO TOGETHER.</span><span>MADE TO BE YOURS.</span></div></div><div class="hero-image">{% if section.settings.image != blank %}{{ section.settings.image | image_url: width: 1600 | image_tag: fetchpriority: 'high', widths: '600,900,1200,1600', sizes: '(min-width: 900px) 50vw, 100vw' }}{% else %}<img src="{{ 'milano-striped-pants-dropping-next-week-0.png' | asset_url }}" width="1023" height="1276" alt="White tee styled with Milano striped pants" fetchpriority="high">{% endif %}<div class="image-label"><span>01 / THE STRIPED EDIT</span><a href="{{ routes.root_url }}#bundles">Shop the look ↗</a></div></div></section><div class="brand-strip"><span>LESS EFFORT. MORE YOU.</span><i>✳</i><span>FROM BEIRUT, WITH INTENTION.</span><i>✳</i><span>GOOD DAYS. GREAT FITS.</span><i>✳</i></div>'''
section('hero',hero,[{'type':'text','id':'heading','label':'Heading','default':'Everyday.\nAnything but ordinary.'},{'type':'image_picker','id':'image','label':'Editorial image'}])
card='''<article class="product-card"><a class="product-photo" href="{{ product.url }}">{% if product.featured_image %}{{ product.featured_image | image_url: width: 900 | image_tag: loading: 'lazy', widths: '300,500,700,900', sizes: '(min-width: 900px) 25vw, 50vw' }}{% endif %}{% if product.images[1] %}{{ product.images[1] | image_url: width: 900 | image_tag: loading: 'lazy', class: 'alternate' }}{% endif %}<span class="badge">{% unless product.available %}Sold out{% else %}{% if product.compare_at_price > product.price %}The good-price edit{% endif %}{% endunless %}</span></a><button class="quick-add" data-product="{{ product.handle }}" aria-label="Choose options for {{ product.title | escape }}">+</button><div class="product-meta"><a href="{{ product.url }}">{{ product.title }}</a><span>{{ product.price | money }}{% if product.compare_at_price > product.price %} <s>{{ product.compare_at_price | money }}</s>{% endif %}</span></div><p class="product-options">{{ product.options_with_values.first.values | join: ' · ' }}</p></article>'''
write('theme/snippets/product-card.liquid',card)
essentials='''<section class="section" id="essentials"><div class="section-heading"><div><p class="eyebrow">THE ROTATION, REFINED</p><h2>Your new regulars.</h2></div><a class="text-link" href="{{ routes.all_products_collection_url }}">Explore all pieces ↗</a></div><div class="product-grid">{% assign featured = section.settings.collection | default: collections.all %}{% for product in featured.products limit: 4 %}{% render 'product-card', product: product %}{% endfor %}</div></section>'''
section('essentials',essentials,[{'type':'collection','id':'collection','label':'Featured collection'}])
bundles='''<section class="section bundle-section" id="bundles"><div class="section-heading"><div><p class="eyebrow">BETTER TOGETHER</p><h2>A whole look.<br>One easy decision.</h2></div><p>Good pieces make great pairs.<br>Choose your fit. Make it your own.</p></div><div class="bundle-grid">{% for block in section.blocks %}{% assign top = block.settings.top %}{% assign bottom = block.settings.bottom %}{% if top != blank and bottom != blank %}<article class="bundle-card" {{ block.shopify_attributes }}><div class="bundle-images">{{ top.featured_image | image_url: width: 700 | image_tag: loading: 'lazy' }}{{ bottom.featured_image | image_url: width: 700 | image_tag: loading: 'lazy' }}<span class="bundle-number">0{{ forloop.index }} / THE OUTFIT EDIT</span></div><div class="bundle-info"><div><h3>{{ block.settings.title }}</h3><p>{{ top.title }} + {{ bottom.title }}</p></div><button class="text-link" data-bundle="{{ top.handle }},{{ bottom.handle }}" data-title="{{ block.settings.title | escape }}">Build your set ↗</button></div></article>{% endif %}{% endfor %}</div></section>'''
bs={'name':'Outfit bundles','max_blocks':3,'settings':[],'blocks':[{'type':'outfit','name':'Outfit','settings':[{'type':'text','id':'title','label':'Title','default':'The daily uniform'},{'type':'product','id':'top','label':'First piece'},{'type':'product','id':'bottom','label':'Second piece'}]}],'presets':[{'name':'Outfit bundles'}]}
write('theme/sections/bundles.liquid',bundles+'{% schema %}'+json.dumps(bs)+'{% endschema %}')
story='''<section class="story" id="story"><div class="story-image"><img src="{{ 'over-size-t-shirt-0.jpg' | asset_url }}" width="566" height="512" alt="Essaint oversized black T-shirt" loading="lazy"></div><div class="story-copy"><p class="eyebrow">ESSAINT / OUR POINT OF VIEW</p><h2>Wear it often.<br>Wear it your way.</h2><p>A wardrobe should feel like you. Easy tees, relaxed stripes, and considered tailoring — pieces that find their way into your everyday.</p><p>Rooted in Lebanon. Ready for wherever the day goes.</p><a class="text-link" href="{{ routes.all_products_collection_url }}">Find your everyday ↗</a></div></section>'''
section('story',story)
footer='''<footer class="footer"><div class="footer-top"><div><a class="wordmark" href="{{ routes.root_url }}">essaint<span>®</span></a><p>Everyday, elevated.<br>Proudly crafted in Lebanon.</p></div><div><h3>Explore</h3><a href="{{ routes.all_products_collection_url }}">All pieces</a><a href="{{ routes.root_url }}#bundles">The outfit edit</a><a href="{{ routes.search_url }}">Search</a></div><div><h3>Here to help</h3><a href="/pages/contact">Contact us</a><a href="https://wa.me/96171236353" target="_blank" rel="noopener">WhatsApp ↗</a>{% for policy in shop.policies %}{% if policy.body != blank %}<a href="{{ policy.url }}">{{ policy.title }}</a>{% endif %}{% endfor %}</div><div class="newsletter"><h3>Stay in the loop.</h3><p>Fresh pieces. New combinations. Essaint in your inbox.</p>{% form 'customer' %}<input type="hidden" name="contact[tags]" value="newsletter"><label class="sr-only" for="NewsletterEmail">Email address</label><div class="email-field"><input id="NewsletterEmail" name="contact[email]" type="email" required placeholder="Your email address" autocomplete="email"><button aria-label="Subscribe">↗</button></div>{{ form.errors | default_errors }}{% if form.posted_successfully? %}<p>You're on the list. Welcome to Essaint.</p>{% endif %}{% endform %}</div></div><div class="footer-bottom"><span>© {{ 'now' | date: '%Y' }} Essaint</span><span>BEIRUT, LEBANON</span><span>Made for your everyday.</span></div></footer>'''
section('footer',footer)
overlays='''<dialog id="shop-dialog" class="shop-dialog"><button class="close" data-close aria-label="Close">×</button><div id="dialog-content"></div></dialog><dialog id="bag-dialog" class="bag-dialog"><div class="drawer-heading"><h2>Your bag <span data-count></span></h2><button data-close class="close" aria-label="Close bag">×</button></div><div id="bag-content"></div></dialog><dialog id="search-dialog" class="search-dialog"><button data-close class="close" aria-label="Close search">×</button><p class="eyebrow">FIND YOUR NEXT REGULAR</p><h2>What are you looking for?</h2><form action="{{ routes.search_url }}" method="get"><input type="hidden" name="type" value="product"><label class="sr-only" for="search-input">Search products</label><input id="search-input" name="q" type="search" placeholder="Try linen, stripes, a perfect tee…" autocomplete="off"><button class="button">Search ↗</button></form><div id="search-results" class="search-results"></div></dialog><p class="toast" id="status" role="status" aria-live="polite"></p>'''
write('theme/snippets/overlays.liquid',overlays)
write('theme/layout/theme.liquid','''<!doctype html><html lang="{{ request.locale.iso_code }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ page_title }}{% unless page_title contains shop.name %} — {{ shop.name }}{% endunless %}</title><meta name="description" content="{{ page_description | default: shop.description | escape }}"><link rel="canonical" href="{{ canonical_url }}"><meta property="og:title" content="{{ page_title | escape }}"><meta property="og:url" content="{{ canonical_url }}"><meta property="og:type" content="website">{{ content_for_header }}{{ 'essaint.css' | asset_url | stylesheet_tag }}<script>window.Essaint={root:{{ routes.root_url | json }},currency:{{ cart.currency.iso_code | json }},preview:false};</script><script src="{{ 'essaint.js' | asset_url }}" defer></script></head><body><a class="skip-link" href="#MainContent">Skip to content</a>{% sections 'header-group' %}<main id="MainContent">{{ content_for_layout }}</main>{% sections 'footer-group' %}{% render 'overlays' %}</body></html>''')
for group in ['header','footer']:write('theme/sections/'+group+'-group.json',json.dumps({'type':group,'name':group.title(),'sections':{'main':{'type':group}},'order':['main']}))
template('index',['hero','essentials','bundles','story'])
idx=json.loads((ROOT/'theme/templates/index.json').read_text());idx['sections']['2']['blocks']={str(i):{'type':'outfit','settings':{'title':title,'top':'over-size-t-shirt','bottom':handle}} for i,(title,handle) in enumerate([('The off-duty pair','milano-striped-pants-dropping-next-week'),('The slow-day set','linen-pants-unisex'),('The city uniform','tailored-pants')])};idx['sections']['2']['block_order']=['0','1','2'];write('theme/templates/index.json',json.dumps(idx,indent=2))
section('main-collection','''<section class="section collection"><p class="eyebrow">THE ESSAINT WARDROBE</p><h1>{{ collection.title }}</h1><div class="rte">{{ collection.description }}</div><form class="filter-bar" method="get"><span>{{ collection.products_count }} pieces</span><label>Sort by <select name="sort_by" onchange="this.form.submit()">{% assign sort = collection.sort_by | default: collection.default_sort_by %}{% for option in collection.sort_options %}<option value="{{ option.value }}" {% if option.value == sort %}selected{% endif %}>{{ option.name }}</option>{% endfor %}</select></label></form>{% paginate collection.products by 24 %}<div class="product-grid">{% for product in collection.products %}{% render 'product-card', product: product %}{% else %}<p>No pieces in this collection yet.</p>{% endfor %}</div><div class="pagination">{{ paginate | default_pagination }}</div>{% endpaginate %}</section>''')
template('collection',['main-collection'])
section('main-product','''<section class="section product-page"><div class="gallery">{% for image in product.images %}{{ image | image_url: width: 1400 | image_tag: loading: 'lazy', widths: '500,900,1400', sizes: '(min-width: 900px) 55vw, 100vw' }}{% endfor %}</div><div class="product-details"><a class="eyebrow" href="{{ routes.all_products_collection_url }}">THE COLLECTION /</a><h1>{{ product.title }}</h1><div class="price" data-product-price>{{ product.selected_or_first_available_variant.price | money }}</div>{% form 'product', product, class: 'native-product-form' %}<label for="variant-{{ section.id }}">Choose your size / color</label><select id="variant-{{ section.id }}" name="id" data-variant-select>{% for variant in product.variants %}<option value="{{ variant.id }}" data-price="{{ variant.price }}" {% unless variant.available %}disabled{% endunless %} {% if variant == product.selected_or_first_available_variant %}selected{% endif %}>{{ variant.title }}{% unless variant.available %} — Sold out{% endunless %}</option>{% endfor %}</select><label for="quantity">Quantity</label><input id="quantity" name="quantity" type="number" value="1" min="1" max="99"><button class="button" type="submit" {% unless product.available %}disabled{% endunless %}>{% if product.available %}Add to bag ↗{% else %}Sold out{% endif %}</button>{{ form | payment_button }}{% endform %}<details open><summary>The details</summary><div class="rte">{{ product.description }}</div></details><details><summary>Delivery & exchanges</summary><p>Complimentary shipping on orders over $100. 7-day easy exchanges.</p><a href="{{ shop.shipping_policy.url }}">Shipping policy</a> · <a href="{{ shop.refund_policy.url }}">Exchange policy</a></details><p class="fit-help">Need help choosing your fit? <a href="https://wa.me/96171236353">Ask us on WhatsApp ↗</a></p></div></section><script type="application/ld+json">{{ product | structured_data }}</script>''')
template('product',['main-product'])
section('main-cart','''<section class="section cart-page"><p class="eyebrow">YOUR EVERYDAY STARTS HERE</p><h1>Your bag.</h1>{% if cart.empty? %}<p>Your bag is waiting for something good.</p><a class="button" href="{{ routes.all_products_collection_url }}">Explore the collection ↗</a>{% else %}<form action="{{ routes.cart_url }}" method="post">{% for item in cart.items %}<div class="cart-row">{{ item.image | image_url: width: 240 | image_tag: loading: 'lazy' }}<div><a href="{{ item.url }}">{{ item.product.title }}</a><p>{{ item.variant.title }}</p><a href="{{ item.url_to_remove }}">Remove</a></div><label>Quantity<input type="number" name="updates[]" value="{{ item.quantity }}" min="0" aria-label="Quantity for {{ item.title | escape }}"></label><span>{{ item.final_line_price | money }}</span></div>{% endfor %}<p>Subtotal {{ cart.total_price | money }}</p>{% for discount in cart.cart_level_discount_applications %}<p>{{ discount.title }} −{{ discount.total_allocated_amount | money }}</p>{% endfor %}<p>Shipping and taxes calculated at checkout.</p><button class="text-link" name="update">Update bag</button><button class="button" name="checkout">Checkout ↗</button></form>{% endif %}</section>''')
template('cart',['main-cart'])
section('main-search','''<section class="section collection"><p class="eyebrow">THE ESSAINT WARDROBE</p><h1>Find your next regular.</h1><form action="{{ routes.search_url }}" class="filter-bar"><input name="q" type="search" value="{{ search.terms | escape }}" placeholder="Search products" aria-label="Search products"><input name="type" type="hidden" value="product"><button class="button">Search</button></form>{% paginate search.results by 24 %}<div class="product-grid">{% for product in search.results %}{% if product.object_type == 'product' %}{% render 'product-card', product: product %}{% endif %}{% else %}{% if search.performed %}<p>No matches. Try a different search.</p>{% endif %}{% endfor %}</div>{{ paginate | default_pagination }}{% endpaginate %}</section>''')
template('search',['main-search'])
section('main-page','''<section class="section prose"><h1>{{ page.title }}</h1><div class="rte">{{ page.content }}</div></section>''');template('page',['main-page'])
section('contact','''<section class="section prose"><p class="eyebrow">HERE TO HELP</p><h1>Let's talk.</h1><p>For sizing, orders, or a little outfit advice, get in touch.</p><a href="https://wa.me/96171236353" class="text-link">WhatsApp +961 71 236 353 ↗</a>{% form 'contact', class: 'contact-form' %}{{ form.errors | default_errors }}{% if form.posted_successfully? %}<p>Thank you. Your message has been sent.</p>{% endif %}<label>Name<input name="contact[name]" autocomplete="name" required></label><label>Email<input name="contact[email]" type="email" autocomplete="email" required></label><label>Message<textarea name="contact[body]" rows="6" required></textarea></label><button class="button">Send message ↗</button>{% endform %}</section>''');template('page.contact',['contact'])
section('main-404','''<section class="section prose"><p class="eyebrow">404 / A WRONG TURN</p><h1>Let's get you<br>back to good.</h1><a class="button" href="{{ routes.all_products_collection_url }}">Shop the collection ↗</a></section>''');template('404',['main-404'])
section('list-collections','''<section class="section"><h1>The collections.</h1><div class="product-grid">{% for collection in collections %}<a href="{{ collection.url }}">{% if collection.image %}{{ collection.image | image_url: width: 800 | image_tag: loading: 'lazy' }}{% endif %}<h2>{{ collection.title }}</h2></a>{% endfor %}</div></section>''');template('list-collections',['list-collections'])
write('theme/config/settings_schema.json',json.dumps([{'name':'theme_info','theme_name':'Essaint Atelier','theme_version':'1.0.0','theme_author':'Essaint','theme_documentation_url':'https://essaint.com','theme_support_url':'https://essaint.com/pages/contact'}],indent=2));write('theme/config/settings_data.json','{"current":{}}');write('theme/locales/en.default.json','{"general":{"accessibility":{"skip_to_content":"Skip to content"}}}')
print('Built theme sections and catalog:',len(P),'products;',len(assets),'images')

# Reapply the current storefront art direction after the base theme is generated.
import runpy
runpy.run_path(str(ROOT / "scripts/redesign.py"))
