"""Imanuel-inspired bundle packs and staggered Essaint photography cards."""
import pathlib,json,re
R=pathlib.Path(__file__).resolve().parents[1]
def write(path,text):(R/path).write_text(text,encoding='utf-8')
pack='''<section class="pack-section" id="bundles" data-pack><div class="refined-heading"><p class="eyebrow">MORE OF WHAT YOU LIVE IN</p><h2>Build a bundle.</h2><p>Choose your favorite piece. Pick your pack.<br>Make every color and size your own.</p></div><div class="pack-card"><div class="pack-product-bar"><div><label for="pack-product-{{ section.id }}">SELECT YOUR PRODUCT</label><select id="pack-product-{{ section.id }}" data-pack-product>{% assign pack_collection = section.settings.collection | default: collections.all %}{% for item in pack_collection.products %}<option value="{{ item.handle }}" {% if item.handle == 'over-size-t-shirt' %}selected{% endif %}>{{ item.title }}</option>{% endfor %}</select></div><a class="text-link" data-pack-link href="{{ routes.all_products_collection_url }}">VIEW PRODUCT ↗</a></div><div class="pack-main"><div class="pack-media"><div class="pack-stage"><img data-pack-image src="{{ 'over-size-t-shirt-0.jpg' | asset_url }}" alt="Oversized T-Shirt" width="566" height="512" loading="lazy"><span data-pack-badge>YOUR 3-PIECE PACK</span></div><p data-pack-title>Oversized T-Shirt</p><div class="pack-thumbs" data-pack-thumbs></div></div><form class="pack-panel"><fieldset class="pack-quantity"><legend>01 / CHOOSE YOUR QUANTITY</legend><div class="pack-tiers">{% for count in (1..3) %}{% case count %}{% when 1 %}{% assign qty = 1 %}{% when 2 %}{% assign qty = 3 %}{% when 3 %}{% assign qty = 6 %}{% endcase %}<button type="button" data-pack-qty="{{ qty }}" aria-pressed="{% if qty == 3 %}true{% else %}false{% endif %}" {% if qty == 3 %}class="active"{% endif %}><strong>{{ qty }}</strong><span>{% if qty == 1 %}THE SINGLE{% elsif qty == 3 %}THE ROTATION{% else %}THE FULL WEEK{% endif %}</span><small data-tier-price>—</small></button>{% endfor %}</div></fieldset><div class="pack-pieces-heading"><span>02 / CONFIGURE EACH PIECE</span><span data-pack-count>3 PIECES</span></div><div data-pack-pieces><p>Loading available sizes and colors…</p></div><div class="pack-checkout"><div class="pack-price"><strong data-pack-total>—</strong><span data-pack-each></span></div><button class="button" data-pack-add disabled>ADD YOUR BUNDLE <span>↗</span></button><p class="pack-message" data-pack-message role="status">Choose your options to build your pack.</p></div><noscript><p>Enable JavaScript to build a pack, or shop products individually.</p></noscript></form></div></div></section>'''
schema={'name':'Product packs','settings':[{'type':'collection','id':'collection','label':'Products available for packs'}],'presets':[{'name':'Product packs'}]}
write('theme/sections/bundle-packs.liquid',pack+'{% schema %}'+json.dumps(schema)+'{% endschema %}')
p=R/'theme/sections/bundles.liquid';s=p.read_text(encoding='utf-8').replace('class="bundle-section" id="bundles"','class="bundle-section bundle-section--soft" id="cross-bundle"').replace('/ THE OUTFIT STUDIO','COMPLETE THE LOOK').replace('YOUR FIT. <em>Your rules.</em>','Pants + Tee.<br><em>Better together.</em>').replace('One top. One bottom. Endless ways to make it yours.','Pair any tee with your favorite trousers. A full look, your way.').replace('THE ART OF EVERYDAY.','YOUR EVERYDAY PAIRING.').replace('BUILD YOUR UNIFORM.','Make it yours.');write('theme/sections/bundles.liquid',s)
wild='''<section class="wild-section" id="in-the-wild"><div class="section-heading"><div><p class="eyebrow">ESSAINT / WORN YOUR WAY</p><h2>In the Wild.</h2></div><a href="{{ routes.all_products_collection_url }}" class="text-link">SHOP THE LOOKS ↗</a></div><div class="wild-cards">{% for block in section.blocks %}{% assign piece = block.settings.product %}<article class="wild-card" {{ block.shopify_attributes }}><a href="{% if piece != blank %}{{ piece.url }}{% else %}{{ routes.all_products_collection_url }}{% endif %}" {% if piece != blank %}data-product="{{ piece.handle }}"{% endif %} aria-label="{% if piece != blank %}Shop {{ piece.title | escape }}{% else %}Shop Essaint{% endif %}">{% if block.settings.image != blank %}{{ block.settings.image | image_url: width: 900 | image_tag: loading: 'lazy', widths: '300,600,900', sizes: '(min-width: 900px) 20vw, 65vw' }}{% else %}{% assign fallback = block.settings.asset %}<img src="{{ fallback | asset_url }}" width="900" height="1200" alt="{{ block.settings.caption | escape }}" loading="lazy">{% endif %}<span class="wild-shop">SHOP THIS LOOK <b>+</b></span></a><p>{{ block.settings.caption }}</p></article>{% endfor %}</div><div class="wild-bottom"><span>OFF THE RACK. OUT IN THE WORLD.</span><a class="text-link" href="https://wa.me/96171236353" target="_blank" rel="noopener">SHARE YOUR ESSAINT LOOK ↗</a></div></section>'''
settings=[{'type':'image_picker','id':'image','label':'Photo'},{'type':'product','id':'product','label':'Featured product'},{'type':'text','id':'caption','label':'Caption','default':'Everyday Essaint'},{'type':'text','id':'asset','label':'Fallback theme image','default':'wild-1.jpg'}]
write('theme/sections/in-the-wild.liquid',wild+'{% schema %}'+json.dumps({'name':'In the Wild','settings':[],'max_blocks':10,'blocks':[{'type':'photo','name':'Photo card','settings':settings}],'presets':[{'name':'In the Wild'}]})+'{% endschema %}')
index=json.loads((R/'theme/templates/index.json').read_text());index['sections']['packs']={'type':'bundle-packs'}
photos=[('wild-1.jpg','tailored-pants','Dressed for the day.'),('wild-2.jpg','milano-striped-pants-dropping-next-week','Out after hours.'),('essaint-campaign-original.jpg','skyline-striped-pants','Taking the slow way.'),('wild-3.jpg','purple-stripped-pants','A little color. A lot of you.'),('wild-4.jpg','pinstriped-pants','Everyday, elsewhere.')]
index['sections']['wild']={'type':'in-the-wild','blocks':{str(i):{'type':'photo','settings':{'asset':asset,'product':handle,'caption':caption}} for i,(asset,handle,caption) in enumerate(photos)},'block_order':[str(i) for i in range(len(photos))]}
index['order']=['0','1','packs','2','3','wild'];write('theme/templates/index.json',json.dumps(index,indent=2))
layout=(R/'theme/layout/theme.liquid').read_text(encoding='utf-8')
if "'packs.js'" not in layout:layout=layout.replace('</head>',"<script src=\"{{ 'packs.js' | asset_url }}\" defer></script></head>")
write('theme/layout/theme.liquid',layout)
write('data/wild-cards.json',json.dumps(photos,indent=2));print('Built product packs, refined cross bundles and In the Wild cards.')

layout=(R / "theme/layout/theme.liquid").read_text(encoding="utf-8")
if "bundle-refinement.css" not in layout:layout=layout.replace("</head>","{{ 'bundle-refinement.css' | asset_url | stylesheet_tag }}</head>")
write("theme/layout/theme.liquid",layout)

config=json.loads((R / "theme/config/settings_schema.json").read_text(encoding="utf-8"));config[0]["theme_version"]="2.1.0";write("theme/config/settings_schema.json",json.dumps(config,indent=2))
import runpy
runpy.run_path(str(R / 'scripts/mobile.py'))
