const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
async function main(){const dom=new JSDOM(fs.readFileSync('dist/index.html','utf8'),{url:'http://localhost:4173/',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};w.eval("window.Essaint={preview:true,root:'/',currency:'USD'}");for(const file of ['catalog.js','essaint.js','preview.js'])w.eval(fs.readFileSync('dist/assets/'+file,'utf8'));const wait=()=>new Promise(r=>setTimeout(r,50));
assert.equal(w.EssaintCatalog.length,12);assert.equal(w.EssaintCatalog.reduce((s,p)=>s+p.variants.length,0),66);
await w.EssaintUI.quick('purple-stripped-pants');assert(w.document.querySelector('#quick-form button').disabled,'Sold-out product cannot be added');
await w.EssaintUI.quick('over-size-t-shirt');let selected=w.document.querySelector('#quick-variant');const tee=w.EssaintCatalog.find(p=>p.handle==='over-size-t-shirt');assert(tee.variants.find(v=>v.id===Number(selected.value)).available,'First selected option is available');
await w.EssaintUI.bundle('over-size-t-shirt,linen-pants-unisex','The slow-day set');assert.match(w.document.querySelector('#bundle-total').textContent,/56\.00/);const form=w.document.querySelector('#bundle-form');form.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:form.querySelector('button')}));await wait();assert.equal(w.document.querySelectorAll('.bag-item').length,2,'Two bundle components added');assert.equal(w.document.querySelector('[data-count]').textContent,'2');assert(w.document.querySelector('#bag-dialog .bag-summary button').disabled,'Preview checkout disabled');
let plus=w.document.querySelector('.quantity button[data-quantity="2"]');plus.click();await wait();assert.equal(w.document.querySelector('[data-count]').textContent,'3');w.document.querySelector('.quantity button[data-quantity="0"]').click();await wait();assert.equal(w.document.querySelectorAll('.bag-item').length,1);
w.location.hash='shop';await wait();assert.equal(w.document.querySelectorAll('#collection-grid .product-card').length,12);w.document.querySelector('[data-filter="tees"]').click();assert.equal(w.document.querySelectorAll('#collection-grid .product-card').length,2);w.location.hash='product/linen-pants-unisex';await wait();assert.equal(w.document.querySelectorAll('#p-variant option').length,9);assert.equal(w.document.querySelector('h1').textContent,'Everyday.Anything butordinary.');assert.match(w.document.querySelector('.product-details h1').textContent,/Linen Pants/);
for(const img of [...w.document.querySelectorAll('img[src]')]){const src=img.getAttribute('src');if(src.startsWith('assets/'))assert(fs.existsSync('dist/'+src),'Missing image '+src)}
console.log('PASS: catalog counts, sold-out protection, valid default variants, bundle total and add, cart quantity and removal, disabled preview checkout, collection filter, product routing and image references.');dom.window.close();}
main().catch(e=>{console.error(e);process.exit(1)});
