const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
async function main(){const dom=new JSDOM(fs.readFileSync('dist/index.html','utf8'),{url:'http://localhost:4173/',runScripts:'outside-only'}),w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'))};w.eval("window.Essaint={preview:true,root:'/',currency:'USD'}");for(const file of ['catalog.js','essaint.js','studio.js','packs.js','preview.js'])w.eval(fs.readFileSync('dist/assets/'+file,'utf8'));const wait=()=>new Promise(r=>setTimeout(r,50));
assert.equal(w.EssaintCatalog.length,12);assert.equal(w.EssaintCatalog.reduce((s,p)=>s+p.variants.length,0),66);
await wait();assert.equal(w.document.querySelectorAll('[data-edit-grid] .product-card:not([hidden])').length,4);w.document.querySelector('[data-edit-filter="tees"]').click();assert.equal(w.document.querySelectorAll('[data-edit-grid] .product-card:not([hidden])').length,2);w.document.querySelector('[data-edit-filter="all"]').click();
assert.match(w.document.querySelector('[data-studio-total]').textContent,/46\.00/);const bottom=w.document.querySelector('[data-studio-product="bottom"]');bottom.value='purple-stripped-pants';bottom.dispatchEvent(new w.Event('change'));await wait();assert(w.document.querySelector('[data-studio-add]').disabled,'Studio rejects sold-out styles');bottom.value='linen-pants-unisex';bottom.dispatchEvent(new w.Event('change'));await wait();assert.match(w.document.querySelector('[data-studio-total]').textContent,/56\.00/);assert(!w.document.querySelector('[data-studio-add]').disabled,'Studio recovers after choosing an available piece');
await w.EssaintUI.quick('purple-stripped-pants');assert(w.document.querySelector('#quick-form button').disabled,'Sold-out product cannot be added');
await w.EssaintUI.quick('over-size-t-shirt');let selected=w.document.querySelector('#quick-variant');const tee=w.EssaintCatalog.find(p=>p.handle==='over-size-t-shirt');assert(tee.variants.find(v=>v.id===Number(selected.value)).available,'First selected option is available');
await w.EssaintUI.bundle('over-size-t-shirt,linen-pants-unisex','The slow-day set');assert.match(w.document.querySelector('#bundle-total').textContent,/56\.00/);const form=w.document.querySelector('#bundle-form');form.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:form.querySelector('button')}));await wait();assert.equal(w.document.querySelectorAll('.bag-item').length,2,'Two bundle components added');assert.equal(w.document.querySelector('[data-count]').textContent,'2');assert(w.document.querySelector('#bag-dialog .bag-summary button').disabled,'Preview checkout disabled');
let plus=w.document.querySelector('.quantity button[data-quantity="2"]');plus.click();await wait();assert.equal(w.document.querySelector('[data-count]').textContent,'3');w.document.querySelector('.quantity button[data-quantity="0"]').click();await wait();assert.equal(w.document.querySelectorAll('.bag-item').length,1);
const studioForm=w.document.querySelector('.studio-form');studioForm.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:w.document.querySelector('[data-studio-add]')}));await wait();assert.equal(w.document.querySelectorAll('.bag-item').length,2,'Inline studio adds both selected variants');assert.equal(w.document.querySelector('[data-count]').textContent,'3');
w.location.hash='shop';await wait();assert.equal(w.document.querySelectorAll('#collection-grid .product-card').length,12);w.document.querySelector('[data-filter="tees"]').click();assert.equal(w.document.querySelectorAll('#collection-grid .product-card').length,2);w.location.hash='product/linen-pants-unisex';await wait();assert.equal(w.document.querySelectorAll('#p-variant option').length,9);assert.equal(w.document.querySelector('h1').textContent,'OFF DUTY.On purpose.');assert.match(w.document.querySelector('.product-details h1').textContent,/Linen Pants/);
assert.equal(w.document.querySelectorAll('.pack-piece').length,3);assert.match(w.document.querySelector('[data-pack-total]').textContent,/60\.00/);w.document.querySelector('[data-pack-qty="6"]').click();assert.equal(w.document.querySelectorAll('.pack-piece').length,6);assert.match(w.document.querySelector('[data-pack-total]').textContent,/120\.00/);w.document.querySelector('[data-pack-qty="1"]').click();assert.equal(w.document.querySelectorAll('.pack-piece').length,1);w.document.querySelector('[data-pack-qty="3"]').click();const color=w.document.querySelector('[data-piece="0"][data-option="1"]');color.value='Black';color.dispatchEvent(new w.Event('change',{bubbles:true}));assert(w.document.querySelector('[data-pack-add]').disabled,'Sold-out combination blocks pack');color.value='Mocha';color.dispatchEvent(new w.Event('change',{bubbles:true}));assert(!w.document.querySelector('[data-pack-add]').disabled);assert.match(w.document.querySelector('[data-pack-image]').src,/over-size-t-shirt-4.png/);const packForm=w.document.querySelector('.pack-panel');packForm.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:w.document.querySelector('[data-pack-add]')}));await wait();assert.equal(w.document.querySelector('[data-count]').textContent,'6','Three selected pack pieces added to existing bag');assert.equal(w.document.querySelectorAll('.wild-card').length,5);assert.equal(w.document.querySelectorAll('.wild-card [data-product]').length,5);
for(const img of [...w.document.querySelectorAll('img[src]')]){const src=img.getAttribute('src');if(src.startsWith('assets/'))assert(fs.existsSync('dist/'+src),'Missing image '+src)}
console.log('PASS: catalog counts, sold-out protection, valid default variants, bundle total and add, cart quantity and removal, disabled preview checkout, collection filter, product routing and image references.');dom.window.close();}
main().catch(e=>{console.error(e);process.exit(1)});
